 start begin

 end

 functions begin

     number x
     h = "lol"


     function myfunc(text k, number g) begin

         Collection Student(text name, number age)

         Student sofia = "sofia", 20

         sofia.name = "lol"

         Student truls = "truls", 44
         truls.age = 55


     end

     function newfunc(text b) begin

         Collection Car = (text carType)
         Car jaguar
         jaguar.cartype = "cool"


     end



 end