 start begin

 end

 functions begin

     number x
     h = "lol"

     function myfunc(text k, number g) begin

         Collection Student(text name, number age)

         text list list1 = "sofia", "kari", "inga"

         Student sofia = list1 get 0, g

        return sofia get age
     end

     function newFunc begin
     ask person1 "hvad hedder du????"

        return person1 get answer
     end
end